server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: account-service  # ❌ Estaba como "user-service"

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

user-service:
  url: http://localhost:8081

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic  # ❌ Faltaba la "c" en "basic"

# Agregar logging para debugging
logging:
  level:
    com.tcs.account_service.client: DEBUG
    feign: DEBUG